### ISSUE TITLE
Separated component package 

### ISSUE THREAD

**Issue by ibnumusyaffa** [kobaltedev/kobalte#35]
**Is your feature request related to a problem? Please describe.**
Separated component package like radix-ui

**Describe the solution you'd like**
Each primitive can be installed individually so user can adopt them incrementally. example from radix-ui
```
npm install @radix-ui/react-dialog
npm install @radix-ui/react-dropdown-menu
npm install @radix-ui/react-tooltip
```

**Comment by marbemac** [comment]
Curious - what's the driving need for this? Is your bundler unable to tree-shake unused components out?

**Comment by fabien-ml** [comment]
Hi, I will not do it for now because of versioning maintenance nightmare when having multiple packages and the reason mentioned by @marbemac. 

However i've created a feature request on [kobalte.canny.io](https://kobalte.canny.io/feature-requests/p/separated-component-package). If it's very requested I will reconsider it.

**Comment by sindreij** [comment]
I'll second this. When using kobalte with vite the performance when loading the page in development gets really bad. Maybe it's not required to split into packages, but creating multiple entrypoints so that it's possible to import just one component?

**Comment by marbemac** [comment]
> When using kobalte with vite the performance when loading the page in development gets really bad

Do you have a reproduction repo by any chance? Are you sure it is kobalte causing the slowness? It's really not a lot of code so that would be surprising. I'm using vite + kobalte (and many other libraries), and everything is super smooth w hot reloading and everything.

**Comment by sindreij** [comment]
When I look at the network-tab, I can see lots of requests for files from @kobalte/core. Its only an issue on the page load, hot-reloading is super-quick. I'll see if its possible to create a reproduction repo, it might be I have some weird vite configuration :)

**Comment by simbas** [comment]
I do have the same issue. 

Here is a reproduction repo : https://github.com/simbas/repro-kobalte-page-load, it's basically a fresh solid start app using the Kobalte button.

Before adding the Kobalte button:
<img width="286" alt="Capture d’écran 2023-01-29 à 13 27 56" src="https://user-images.githubusercontent.com/1901675/215326506-59b5ae5f-3e01-42a2-bf00-47813cd5a496.png">

after adding the Kobalte button:
<img width="271" alt="Capture d’écran 2023-01-29 à 13 30 13" src="https://user-images.githubusercontent.com/1901675/215326518-eebf379c-4007-4630-a3d0-4dc0fbb91799.png">

The page loads 340 files and it takes 1 or 2 seconds.

**Comment by susickypavel** [comment]
The same thing can be observed with Astro.js. However, it's not a big problem, as others mentioned. It just adds to the start-up time.

**Comment by predaytor** [comment]
When using the Network tab with disabled cache the wait time to load the entire library is very long. It would be nice to have separate packages. (using Astro)

**Comment by spaaacetoast** [comment]
I'm not sure what i'm doing different but on every change I get full page reload, making seeing changes really slow when using kobalte :(

**Comment by tkottke90** [comment]
---
My Project Details
  - Bundler: Vite
  - Kobalte: 0.11.0
---

Like others have said this does seem like a developer experience issue.  When I startup my application I can see about 3 MB of data gets downloaded worth of Kobalte files.  I have actually had it brick Firefox if I even attempt to use the debugger tab.

When I do a production build with Vite, I do see the tree shaking happening: 

![image](https://github.com/kobaltedev/kobalte/assets/26103969/984a9b44-fb87-4fe9-953d-b307433ff8f0)

The first run is without Kobalte and the second includes the _Button_ component.

I do agree with @fabien-ml  that it should not be something that is expensive to maintain.  

> Hi, I will not do it for now because of versioning maintenance nightmare when having multiple packages and the reason mentioned by @marbemac.
> 
> However i've created a feature request on [kobalte.canny.io](https://kobalte.canny.io/feature-requests/p/separated-component-package). If it's very requested I will reconsider it.

Since Turbo is being use to package here I am wondering if this implementation would fulfill the request here:

https://github.com/vercel/turbo/discussions/612#discussioncomment-4175095

I will pull this repo later and try it on my local and let you guys know
